# ----
# Site

title: Justin's Developer Notes
url: "https://www.jwendl.net"
baseurl:
google_analytics_key:
show_full_navigation: true

# Values for the jekyll-seo-tag gem (https://github.com/jekyll/jekyll-seo-tag)
git_edit_address: https://github.com/jwendl/code-notes/edit/docs-branch
logo: /siteicon.png
description: Justin's Developer Notes
author:
  name:
  email:
  twitter: # twitter username without the @ symbol
social:
  name: Justin's Developer Notes
  links:
    - https://github.com/jwendl/code-notes

# -----
# Build
markdown: kramdown
highlighter: rouge
permalink: pretty
kramdown:
  auto_ids:         true
  footnote_nr:      1
  entity_output:    as_char
  toc_levels:       1..6
  enable_coderay:   false
  input:            GFM
  syntax_highlighter: 
                    rouge

gems:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-feed

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENCE

collections:
  docs:
    title: Documentation
    permalink: /:path/
    output: true

defaults:
  -
    scope:
      path: ""
    values:
      layout: default
  -
    scope:
      path: ""
      type: "docs"
    values:
      seo:
        type: Article
      _comments:
        category: Group navigation links with this field
        order: Used to sort links in the navigation
      _options:
        content:
          width: 800
          height: 2000
  -
    scope:
      path: ""
      type: "posts"
    values:
      _comments:
        type: Marks the impact of this release

# -----------
# CloudCannon

types:
  - minor
  - major
