# Site settings
title: Justin's Dev Notes
email: jwendl@hotmail.com
description: >
  Jekyll Template for Project Websites
  providing documentation and blog post pages.

baseurl: "/code-notes" # the subpath of your site, e.g. /blog/
url: https://www.jwendl.net/code-notes # the base hostname & protocol for your site
git_address: https://github.com/jwendl/code-notes
git_edit_address: https://github.com/jwendl/code-notes/edit/docs-branch

# theme options from https://bootswatch.com/
# comment out this to use default Bootstrap
bootwatch: paper

# Build settings
markdown: kramdown
highlighter: rouge
gems:
  - jekyll-feed
  - jekyll-redirect-from
  - jekyll-seo-tag
  - jekyll-sitemap

exclude:
  - .idea/
  - .gitignore
  - README.md
timezone: Europe/Berlin
defaults:
- scope:
    path: _posts
    type: posts
  values:
    layout: post
    sectionid: blog

- scope:
    path: _docs
    type: docs
  values:
    layout: docs
    sectionid: docs
    seo:
      type: "WebPage"

collections:
  docs:
    permalink: /:collection/:path/
    output: true
  posts:
    permalink: /blog/:year/:month/:day/:title/
    output: true
